Configuration summary:
Available actions: web_search, geolocate, image_search, reverse_search
llm: gemini-2.0-flash-lite-001
benchmark_name: ukraine_russia
tools_config:
    searcher:
        limit_per_search: 3
        search_engine_config:
            google: null
            google_vision: null
    geolocator: null
experiment_name: no_web_search
fact_checker_kwargs:
    decompose: false
    decontextualize: false
    filter_check_worthy: false
    interpret: false
    max_iterations: 3
    max_result_len: 64000
    procedure_variant: summary/dynamic
llm_kwargs:
    temperature: 0.01
benchmark_kwargs:
    variant: dev
allowed_actions:
- image_search
- reverse_search
- geolocate
n_samples: null
sample_ids: null
random_sampling: false
print_log_level: info
continue_experiment_dir: null
n_workers: 4

Started Worker 0 with PID 49.
Started Worker 1 with PID 50.
Started Worker 2 with PID 51.
Started Worker 3 with PID 52.
Worker 3 encountered an error while processing claim 35:
Traceback (most recent call last):
  File "/defame/defame/eval/evaluate.py", line 847, in fact_check
    _, docs, metas = fc.check_content(content)
  File "/defame/defame/fact_checker.py", line 126, in check_content
    doc, meta = self.verify_claim(claim)
  File "/defame/defame/fact_checker.py", line 160, in verify_claim
    label, meta = self.procedure.apply_to(doc)
  File "/defame/defame/procedure/variants/summary_based/dynamic.py", line 25, in apply_to
    self._develop(doc)
  File "/defame/defame/procedure/procedure.py", line 44, in _develop
    response = self.llm.generate(prompt)
  File "/defame/defame/common/modeling.py", line 315, in generate
    if n_attempts > 0 and prompt.retry_instruction is not None:
AttributeError: 'DevelopPrompt' object has no attribute 'retry_instruction'

All workers are terminated.
All outputs saved in /defame/out/ukraine_russia/ukraine_russia/summary/dynamic/gemini-2.0-flash-lite-001/2025-08-29_22-35 no_web_search.
