Configuration summary:
Available actions: web_search, geolocate, image_search, reverse_search
llm: gemini-2.0-flash-lite-001
benchmark_name: gaza_israel
tools_config:
    searcher:
        limit_per_search: 3
        search_engine_config:
            google: null
            google_vision: null
    geolocator: null
experiment_name: default
fact_checker_kwargs:
    decompose: false
    decontextualize: false
    filter_check_worthy: false
    interpret: false
    max_iterations: 3
    max_result_len: 64000
    procedure_variant: summary/dynamic
llm_kwargs:
    temperature: 0.01
benchmark_kwargs:
    variant: dev
allowed_actions:
- web_search
- image_search
- reverse_search
- geolocate
n_samples: null
sample_ids: null
random_sampling: false
print_log_level: info
continue_experiment_dir: null
n_workers: 4

Started Worker 0 with PID 50.
Started Worker 1 with PID 51.
Started Worker 2 with PID 52.
Started Worker 3 with PID 53.
Worker 0 encountered an error while processing claim 34:
Traceback (most recent call last):
  File "/defame/defame/eval/evaluate.py", line 847, in fact_check
    _, docs, metas = fc.check_content(content)
  File "/defame/defame/fact_checker.py", line 126, in check_content
    doc, meta = self.verify_claim(claim)
  File "/defame/defame/fact_checker.py", line 169, in verify_claim
    doc.justification = self.doc_summarizer.summarize(doc)
  File "/defame/defame/modules/doc_summarizer.py", line 15, in summarize
    summary = self.llm.generate(summarize_doc_prompt)
  File "/defame/defame/common/modeling.py", line 315, in generate
    if n_attempts > 0 and prompt.retry_instruction is not None:
AttributeError: 'SummarizeDocPrompt' object has no attribute 'retry_instruction'

Worker 0 encountered an error while processing claim 96:
Traceback (most recent call last):
  File "/defame/defame/eval/evaluate.py", line 847, in fact_check
    _, docs, metas = fc.check_content(content)
  File "/defame/defame/fact_checker.py", line 126, in check_content
    doc, meta = self.verify_claim(claim)
  File "/defame/defame/fact_checker.py", line 160, in verify_claim
    label, meta = self.procedure.apply_to(doc)
  File "/defame/defame/procedure/variants/summary_based/dynamic.py", line 23, in apply_to
    evidences = self.actor.perform(actions, doc)
  File "/defame/defame/modules/actor.py", line 19, in perform
    all_evidence.append(self._perform_single(action, doc, summarize=summarize))
  File "/defame/defame/modules/actor.py", line 24, in _perform_single
    return tool.perform(action, summarize=summarize, doc=doc)
  File "/defame/defame/tools/tool.py", line 20, in perform
    summary = self._summarize(result, **kwargs) if summarize else None
  File "/defame/defame/tools/search/searcher.py", line 201, in _summarize
    return self._summarize_summaries(result, doc)
  File "/defame/defame/tools/search/searcher.py", line 254, in _summarize_summaries
    return MultimediaSnippet(self.llm.generate(summarize_prompt))
  File "/defame/defame/common/modeling.py", line 315, in generate
    if n_attempts > 0 and prompt.retry_instruction is not None:
AttributeError: 'Prompt' object has no attribute 'retry_instruction'

All workers are terminated.
All outputs saved in /defame/out/gaza_israel/gaza_israel/summary/dynamic/gemini-2.0-flash-lite-001/2025-08-29_19-27 default.
